export const notifications = [
  {
    id: 1,
    title: "Candidate Shortlisted",
    message: "Rahul Sharma has been shortlisted for Registered Nurse.",
    type: "candidate",
    priority: "medium",
    read: false,
    selected: false,
    createdAt: "2 hours ago",
  },
  {
    id: 2,
    title: "Interview Scheduled",
    message: "Interview has been scheduled for Priya Patel.",
    type: "interview",
    priority: "high",
    read: false,
    selected: false,
    createdAt: "Yesterday",
  },
  {
    id: 3,
    title: "Visa Approved",
    message: "Visa approved for Ahmed Khan.",
    type: "deployment",
    priority: "high",
    read: true,
    selected: false,
    createdAt: "3 days ago",
  },
  {
    id: 4,
    title: "System Maintenance",
    message: "Scheduled maintenance on Sunday from 2–4 AM.",
    type: "system",
    priority: "low",
    read: true,
    selected: false,
    createdAt: "5 days ago",
  },
  {
    id: 1,
    title: "Candidate Shortlisted",
    message: "Rahul Sharma has been shortlisted for Registered Nurse.",
    type: "candidate",
    priority: "medium",
    read: false,
    selected: false,
    createdAt: "2 hours ago",
    link: "/Employer/candidates/CAN-001",
  },
];
