import { Router } from "express";
import jobsRoutes from "./jobs";
import applicationRoutes from "./application";
import employerPortalRoutes from "./employerPortal";
import applyRoutes from "./apply";
import uploadRoutes from "./upload";
import dashboardRoutes from "./dashboard";
import authRoutes from "./auth";
import candidatePortalRoutes from "./candidatePortal";
import adminCandidateRoutes from "./adminCandidate";
import adminEmployerRoutes from "./adminEmployer";
import requirementsRoutes from "./requirements";
import countriesRoutes from "./countries";
const router = Router();

router.use("/admin/candidates", adminCandidateRoutes);
router.use("/admin/employers", adminEmployerRoutes);
router.use("/admin/jobs", jobsRoutes);
router.use("/admin/applications", applicationRoutes);
router.use("/admin/dashboard", dashboardRoutes);
router.use("/admin/countries", countriesRoutes);
router.use("/applications", applicationRoutes);
router.use("/jobs", jobsRoutes);
router.use("/employer", employerPortalRoutes);
router.use("/apply", applyRoutes);
router.use("/upload", uploadRoutes);
router.use("/auth", authRoutes);
router.use("/candidate", candidatePortalRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/admin/requirements", requirementsRoutes);
export default router;
