/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacypolicyRouteImport } from './routes/privacypolicy'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/Services/index'
import { Route as ServicesVisaRouteImport } from './routes/Services/Visa'
import { Route as ServicesTrainingRouteImport } from './routes/Services/Training'
import { Route as ServicesTechnicalRecRouteImport } from './routes/Services/Technical-rec'
import { Route as ServicesPrometricCoachingRouteImport } from './routes/Services/Prometric-coaching'
import { Route as ServicesParaMedicalTechRouteImport } from './routes/Services/ParaMedical-tech'
import { Route as ServicesNursingRecRouteImport } from './routes/Services/Nursing-rec'
import { Route as ServicesNursesRouteImport } from './routes/Services/Nurses'
import { Route as ServicesMockInterviewsRouteImport } from './routes/Services/Mock-Interviews'
import { Route as ServicesHealthcareRecRouteImport } from './routes/Services/Healthcare-rec'
import { Route as ServicesGroomingRouteImport } from './routes/Services/Grooming'
import { Route as ServicesDocumentationRouteImport } from './routes/Services/Documentation'
import { Route as ServicesDoctorsRouteImport } from './routes/Services/Doctors'
import { Route as EmployerSettingsRouteImport } from './routes/Employer/settings'
import { Route as EmployerRequirementsRouteImport } from './routes/Employer/requirements'
import { Route as EmployerMyCompanyRouteImport } from './routes/Employer/my-company'
import { Route as EmployerJobsRouteImport } from './routes/Employer/jobs'
import { Route as EmployerEmployerRouteImport } from './routes/Employer/employer'
import { Route as EmployerDashboardRouteImport } from './routes/Employer/dashboard'
import { Route as EmployerCandidateRouteImport } from './routes/Employer/candidate'
import { Route as EmployerApplicationsRouteImport } from './routes/Employer/applications'
import { Route as CountriesUKRouteImport } from './routes/Countries/UK'
import { Route as CountriesUAERouteImport } from './routes/Countries/UAE'
import { Route as CountriesSingaporeRouteImport } from './routes/Countries/Singapore'
import { Route as CountriesSaudiArabiaRouteImport } from './routes/Countries/SaudiArabia'
import { Route as CountriesRussiaRouteImport } from './routes/Countries/Russia'
import { Route as CountriesQatarRouteImport } from './routes/Countries/Qatar'
import { Route as CountriesOmanRouteImport } from './routes/Countries/Oman'
import { Route as CountriesNewZealandRouteImport } from './routes/Countries/New-Zealand'
import { Route as CountriesMaltaRouteImport } from './routes/Countries/Malta'
import { Route as CountriesMalaysiaRouteImport } from './routes/Countries/Malaysia'
import { Route as CountriesKuwaitRouteImport } from './routes/Countries/Kuwait'
import { Route as CountriesIrelandRouteImport } from './routes/Countries/Ireland'
import { Route as CountriesGermanyRouteImport } from './routes/Countries/Germany'
import { Route as CountriesDenmarkRouteImport } from './routes/Countries/Denmark'
import { Route as CountriesCanadaRouteImport } from './routes/Countries/Canada'
import { Route as CountriesAustraliaRouteImport } from './routes/Countries/Australia'
import { Route as CandidatesSavedJobsRouteImport } from './routes/Candidates/saved-jobs'
import { Route as CandidatesResumeRouteImport } from './routes/Candidates/resume'
import { Route as CandidatesProfileRouteImport } from './routes/Candidates/profile'
import { Route as CandidatesNotificationsRouteImport } from './routes/Candidates/notifications'
import { Route as CandidatesJobsRouteImport } from './routes/Candidates/jobs'
import { Route as CandidatesDashboardRouteImport } from './routes/Candidates/dashboard'
import { Route as CandidatesCandidateRouteImport } from './routes/Candidates/candidate'
import { Route as CandidatesApplicationsRouteImport } from './routes/Candidates/applications'
import { Route as AdminSettingsRouteImport } from './routes/Admin/settings'
import { Route as AdminRequirementsRouteImport } from './routes/Admin/requirements'
import { Route as AdminJobsRouteImport } from './routes/Admin/jobs'
import { Route as AdminEmployerRouteImport } from './routes/Admin/employer'
import { Route as AdminDashboardRouteImport } from './routes/Admin/dashboard'
import { Route as AdminCountriesRouteImport } from './routes/Admin/countries'
import { Route as AdminCandidatesRouteImport } from './routes/Admin/candidates'
import { Route as AdminApplicationsRouteImport } from './routes/Admin/applications'
import { Route as CandidatesJobsIdRouteImport } from './routes/Candidates/jobs.$id'
import { Route as CandidatesApplicationsIdRouteImport } from './routes/Candidates/applications.$id'
import { Route as AdminJobIdRouteImport } from './routes/Admin/job.$id'
import { Route as AdminEmployerIdRouteImport } from './routes/Admin/employer.$id'
import { Route as AdminCandidateIdRouteImport } from './routes/Admin/candidate.$id'
import { Route as AdminApplicationIdRouteImport } from './routes/Admin/application.$id'

const PrivacypolicyRoute = PrivacypolicyRouteImport.update({
  id: '/privacypolicy',
  path: '/privacypolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/Services/',
  path: '/Services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/Services/Visa',
  path: '/Services/Visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrainingRoute = ServicesTrainingRouteImport.update({
  id: '/Services/Training',
  path: '/Services/Training',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTechnicalRecRoute = ServicesTechnicalRecRouteImport.update({
  id: '/Services/Technical-rec',
  path: '/Services/Technical-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrometricCoachingRoute =
  ServicesPrometricCoachingRouteImport.update({
    id: '/Services/Prometric-coaching',
    path: '/Services/Prometric-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesParaMedicalTechRoute = ServicesParaMedicalTechRouteImport.update({
  id: '/Services/ParaMedical-tech',
  path: '/Services/ParaMedical-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNursingRecRoute = ServicesNursingRecRouteImport.update({
  id: '/Services/Nursing-rec',
  path: '/Services/Nursing-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNursesRoute = ServicesNursesRouteImport.update({
  id: '/Services/Nurses',
  path: '/Services/Nurses',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMockInterviewsRoute = ServicesMockInterviewsRouteImport.update({
  id: '/Services/Mock-Interviews',
  path: '/Services/Mock-Interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHealthcareRecRoute = ServicesHealthcareRecRouteImport.update({
  id: '/Services/Healthcare-rec',
  path: '/Services/Healthcare-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGroomingRoute = ServicesGroomingRouteImport.update({
  id: '/Services/Grooming',
  path: '/Services/Grooming',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDocumentationRoute = ServicesDocumentationRouteImport.update({
  id: '/Services/Documentation',
  path: '/Services/Documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDoctorsRoute = ServicesDoctorsRouteImport.update({
  id: '/Services/Doctors',
  path: '/Services/Doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerSettingsRoute = EmployerSettingsRouteImport.update({
  id: '/Employer/settings',
  path: '/Employer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRequirementsRoute = EmployerRequirementsRouteImport.update({
  id: '/Employer/requirements',
  path: '/Employer/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerMyCompanyRoute = EmployerMyCompanyRouteImport.update({
  id: '/Employer/my-company',
  path: '/Employer/my-company',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/Employer/jobs',
  path: '/Employer/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerEmployerRoute = EmployerEmployerRouteImport.update({
  id: '/Employer/employer',
  path: '/Employer/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/Employer/dashboard',
  path: '/Employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCandidateRoute = EmployerCandidateRouteImport.update({
  id: '/Employer/candidate',
  path: '/Employer/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/Employer/applications',
  path: '/Employer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesUKRoute = CountriesUKRouteImport.update({
  id: '/Countries/UK',
  path: '/Countries/UK',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesUAERoute = CountriesUAERouteImport.update({
  id: '/Countries/UAE',
  path: '/Countries/UAE',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSingaporeRoute = CountriesSingaporeRouteImport.update({
  id: '/Countries/Singapore',
  path: '/Countries/Singapore',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSaudiArabiaRoute = CountriesSaudiArabiaRouteImport.update({
  id: '/Countries/SaudiArabia',
  path: '/Countries/SaudiArabia',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRussiaRoute = CountriesRussiaRouteImport.update({
  id: '/Countries/Russia',
  path: '/Countries/Russia',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesQatarRoute = CountriesQatarRouteImport.update({
  id: '/Countries/Qatar',
  path: '/Countries/Qatar',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesOmanRoute = CountriesOmanRouteImport.update({
  id: '/Countries/Oman',
  path: '/Countries/Oman',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesNewZealandRoute = CountriesNewZealandRouteImport.update({
  id: '/Countries/New-Zealand',
  path: '/Countries/New-Zealand',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesMaltaRoute = CountriesMaltaRouteImport.update({
  id: '/Countries/Malta',
  path: '/Countries/Malta',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesMalaysiaRoute = CountriesMalaysiaRouteImport.update({
  id: '/Countries/Malaysia',
  path: '/Countries/Malaysia',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesKuwaitRoute = CountriesKuwaitRouteImport.update({
  id: '/Countries/Kuwait',
  path: '/Countries/Kuwait',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIrelandRoute = CountriesIrelandRouteImport.update({
  id: '/Countries/Ireland',
  path: '/Countries/Ireland',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesGermanyRoute = CountriesGermanyRouteImport.update({
  id: '/Countries/Germany',
  path: '/Countries/Germany',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesDenmarkRoute = CountriesDenmarkRouteImport.update({
  id: '/Countries/Denmark',
  path: '/Countries/Denmark',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCanadaRoute = CountriesCanadaRouteImport.update({
  id: '/Countries/Canada',
  path: '/Countries/Canada',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesAustraliaRoute = CountriesAustraliaRouteImport.update({
  id: '/Countries/Australia',
  path: '/Countries/Australia',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesSavedJobsRoute = CandidatesSavedJobsRouteImport.update({
  id: '/Candidates/saved-jobs',
  path: '/Candidates/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesResumeRoute = CandidatesResumeRouteImport.update({
  id: '/Candidates/resume',
  path: '/Candidates/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesProfileRoute = CandidatesProfileRouteImport.update({
  id: '/Candidates/profile',
  path: '/Candidates/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesNotificationsRoute = CandidatesNotificationsRouteImport.update({
  id: '/Candidates/notifications',
  path: '/Candidates/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesJobsRoute = CandidatesJobsRouteImport.update({
  id: '/Candidates/jobs',
  path: '/Candidates/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesDashboardRoute = CandidatesDashboardRouteImport.update({
  id: '/Candidates/dashboard',
  path: '/Candidates/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateRoute = CandidatesCandidateRouteImport.update({
  id: '/Candidates/candidate',
  path: '/Candidates/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesApplicationsRoute = CandidatesApplicationsRouteImport.update({
  id: '/Candidates/applications',
  path: '/Candidates/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/Admin/settings',
  path: '/Admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequirementsRoute = AdminRequirementsRouteImport.update({
  id: '/Admin/requirements',
  path: '/Admin/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/Admin/jobs',
  path: '/Admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployerRoute = AdminEmployerRouteImport.update({
  id: '/Admin/employer',
  path: '/Admin/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/Admin/dashboard',
  path: '/Admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/Admin/countries',
  path: '/Admin/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/Admin/candidates',
  path: '/Admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/Admin/applications',
  path: '/Admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesJobsIdRoute = CandidatesJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidatesJobsRoute,
} as any)
const CandidatesApplicationsIdRoute =
  CandidatesApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => CandidatesApplicationsRoute,
  } as any)
const AdminJobIdRoute = AdminJobIdRouteImport.update({
  id: '/Admin/job/$id',
  path: '/Admin/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployerIdRoute = AdminEmployerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEmployerRoute,
} as any)
const AdminCandidateIdRoute = AdminCandidateIdRouteImport.update({
  id: '/Admin/candidate/$id',
  path: '/Admin/candidate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationIdRoute = AdminApplicationIdRouteImport.update({
  id: '/Admin/application/$id',
  path: '/Admin/application/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/employers': typeof EmployersRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/Admin/applications': typeof AdminApplicationsRoute
  '/Admin/candidates': typeof AdminCandidatesRoute
  '/Admin/countries': typeof AdminCountriesRoute
  '/Admin/dashboard': typeof AdminDashboardRoute
  '/Admin/employer': typeof AdminEmployerRouteWithChildren
  '/Admin/jobs': typeof AdminJobsRoute
  '/Admin/requirements': typeof AdminRequirementsRoute
  '/Admin/settings': typeof AdminSettingsRoute
  '/Candidates/applications': typeof CandidatesApplicationsRouteWithChildren
  '/Candidates/candidate': typeof CandidatesCandidateRoute
  '/Candidates/dashboard': typeof CandidatesDashboardRoute
  '/Candidates/jobs': typeof CandidatesJobsRouteWithChildren
  '/Candidates/notifications': typeof CandidatesNotificationsRoute
  '/Candidates/profile': typeof CandidatesProfileRoute
  '/Candidates/resume': typeof CandidatesResumeRoute
  '/Candidates/saved-jobs': typeof CandidatesSavedJobsRoute
  '/Countries/Australia': typeof CountriesAustraliaRoute
  '/Countries/Canada': typeof CountriesCanadaRoute
  '/Countries/Denmark': typeof CountriesDenmarkRoute
  '/Countries/Germany': typeof CountriesGermanyRoute
  '/Countries/Ireland': typeof CountriesIrelandRoute
  '/Countries/Kuwait': typeof CountriesKuwaitRoute
  '/Countries/Malaysia': typeof CountriesMalaysiaRoute
  '/Countries/Malta': typeof CountriesMaltaRoute
  '/Countries/New-Zealand': typeof CountriesNewZealandRoute
  '/Countries/Oman': typeof CountriesOmanRoute
  '/Countries/Qatar': typeof CountriesQatarRoute
  '/Countries/Russia': typeof CountriesRussiaRoute
  '/Countries/SaudiArabia': typeof CountriesSaudiArabiaRoute
  '/Countries/Singapore': typeof CountriesSingaporeRoute
  '/Countries/UAE': typeof CountriesUAERoute
  '/Countries/UK': typeof CountriesUKRoute
  '/Employer/applications': typeof EmployerApplicationsRoute
  '/Employer/candidate': typeof EmployerCandidateRoute
  '/Employer/dashboard': typeof EmployerDashboardRoute
  '/Employer/employer': typeof EmployerEmployerRoute
  '/Employer/jobs': typeof EmployerJobsRoute
  '/Employer/my-company': typeof EmployerMyCompanyRoute
  '/Employer/requirements': typeof EmployerRequirementsRoute
  '/Employer/settings': typeof EmployerSettingsRoute
  '/Services/Doctors': typeof ServicesDoctorsRoute
  '/Services/Documentation': typeof ServicesDocumentationRoute
  '/Services/Grooming': typeof ServicesGroomingRoute
  '/Services/Healthcare-rec': typeof ServicesHealthcareRecRoute
  '/Services/Mock-Interviews': typeof ServicesMockInterviewsRoute
  '/Services/Nurses': typeof ServicesNursesRoute
  '/Services/Nursing-rec': typeof ServicesNursingRecRoute
  '/Services/ParaMedical-tech': typeof ServicesParaMedicalTechRoute
  '/Services/Prometric-coaching': typeof ServicesPrometricCoachingRoute
  '/Services/Technical-rec': typeof ServicesTechnicalRecRoute
  '/Services/Training': typeof ServicesTrainingRoute
  '/Services/Visa': typeof ServicesVisaRoute
  '/Services/': typeof ServicesIndexRoute
  '/Admin/application/$id': typeof AdminApplicationIdRoute
  '/Admin/candidate/$id': typeof AdminCandidateIdRoute
  '/Admin/employer/$id': typeof AdminEmployerIdRoute
  '/Admin/job/$id': typeof AdminJobIdRoute
  '/Candidates/applications/$id': typeof CandidatesApplicationsIdRoute
  '/Candidates/jobs/$id': typeof CandidatesJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/employers': typeof EmployersRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/Admin/applications': typeof AdminApplicationsRoute
  '/Admin/candidates': typeof AdminCandidatesRoute
  '/Admin/countries': typeof AdminCountriesRoute
  '/Admin/dashboard': typeof AdminDashboardRoute
  '/Admin/employer': typeof AdminEmployerRouteWithChildren
  '/Admin/jobs': typeof AdminJobsRoute
  '/Admin/requirements': typeof AdminRequirementsRoute
  '/Admin/settings': typeof AdminSettingsRoute
  '/Candidates/applications': typeof CandidatesApplicationsRouteWithChildren
  '/Candidates/candidate': typeof CandidatesCandidateRoute
  '/Candidates/dashboard': typeof CandidatesDashboardRoute
  '/Candidates/jobs': typeof CandidatesJobsRouteWithChildren
  '/Candidates/notifications': typeof CandidatesNotificationsRoute
  '/Candidates/profile': typeof CandidatesProfileRoute
  '/Candidates/resume': typeof CandidatesResumeRoute
  '/Candidates/saved-jobs': typeof CandidatesSavedJobsRoute
  '/Countries/Australia': typeof CountriesAustraliaRoute
  '/Countries/Canada': typeof CountriesCanadaRoute
  '/Countries/Denmark': typeof CountriesDenmarkRoute
  '/Countries/Germany': typeof CountriesGermanyRoute
  '/Countries/Ireland': typeof CountriesIrelandRoute
  '/Countries/Kuwait': typeof CountriesKuwaitRoute
  '/Countries/Malaysia': typeof CountriesMalaysiaRoute
  '/Countries/Malta': typeof CountriesMaltaRoute
  '/Countries/New-Zealand': typeof CountriesNewZealandRoute
  '/Countries/Oman': typeof CountriesOmanRoute
  '/Countries/Qatar': typeof CountriesQatarRoute
  '/Countries/Russia': typeof CountriesRussiaRoute
  '/Countries/SaudiArabia': typeof CountriesSaudiArabiaRoute
  '/Countries/Singapore': typeof CountriesSingaporeRoute
  '/Countries/UAE': typeof CountriesUAERoute
  '/Countries/UK': typeof CountriesUKRoute
  '/Employer/applications': typeof EmployerApplicationsRoute
  '/Employer/candidate': typeof EmployerCandidateRoute
  '/Employer/dashboard': typeof EmployerDashboardRoute
  '/Employer/employer': typeof EmployerEmployerRoute
  '/Employer/jobs': typeof EmployerJobsRoute
  '/Employer/my-company': typeof EmployerMyCompanyRoute
  '/Employer/requirements': typeof EmployerRequirementsRoute
  '/Employer/settings': typeof EmployerSettingsRoute
  '/Services/Doctors': typeof ServicesDoctorsRoute
  '/Services/Documentation': typeof ServicesDocumentationRoute
  '/Services/Grooming': typeof ServicesGroomingRoute
  '/Services/Healthcare-rec': typeof ServicesHealthcareRecRoute
  '/Services/Mock-Interviews': typeof ServicesMockInterviewsRoute
  '/Services/Nurses': typeof ServicesNursesRoute
  '/Services/Nursing-rec': typeof ServicesNursingRecRoute
  '/Services/ParaMedical-tech': typeof ServicesParaMedicalTechRoute
  '/Services/Prometric-coaching': typeof ServicesPrometricCoachingRoute
  '/Services/Technical-rec': typeof ServicesTechnicalRecRoute
  '/Services/Training': typeof ServicesTrainingRoute
  '/Services/Visa': typeof ServicesVisaRoute
  '/Services': typeof ServicesIndexRoute
  '/Admin/application/$id': typeof AdminApplicationIdRoute
  '/Admin/candidate/$id': typeof AdminCandidateIdRoute
  '/Admin/employer/$id': typeof AdminEmployerIdRoute
  '/Admin/job/$id': typeof AdminJobIdRoute
  '/Candidates/applications/$id': typeof CandidatesApplicationsIdRoute
  '/Candidates/jobs/$id': typeof CandidatesJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/employers': typeof EmployersRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/Admin/applications': typeof AdminApplicationsRoute
  '/Admin/candidates': typeof AdminCandidatesRoute
  '/Admin/countries': typeof AdminCountriesRoute
  '/Admin/dashboard': typeof AdminDashboardRoute
  '/Admin/employer': typeof AdminEmployerRouteWithChildren
  '/Admin/jobs': typeof AdminJobsRoute
  '/Admin/requirements': typeof AdminRequirementsRoute
  '/Admin/settings': typeof AdminSettingsRoute
  '/Candidates/applications': typeof CandidatesApplicationsRouteWithChildren
  '/Candidates/candidate': typeof CandidatesCandidateRoute
  '/Candidates/dashboard': typeof CandidatesDashboardRoute
  '/Candidates/jobs': typeof CandidatesJobsRouteWithChildren
  '/Candidates/notifications': typeof CandidatesNotificationsRoute
  '/Candidates/profile': typeof CandidatesProfileRoute
  '/Candidates/resume': typeof CandidatesResumeRoute
  '/Candidates/saved-jobs': typeof CandidatesSavedJobsRoute
  '/Countries/Australia': typeof CountriesAustraliaRoute
  '/Countries/Canada': typeof CountriesCanadaRoute
  '/Countries/Denmark': typeof CountriesDenmarkRoute
  '/Countries/Germany': typeof CountriesGermanyRoute
  '/Countries/Ireland': typeof CountriesIrelandRoute
  '/Countries/Kuwait': typeof CountriesKuwaitRoute
  '/Countries/Malaysia': typeof CountriesMalaysiaRoute
  '/Countries/Malta': typeof CountriesMaltaRoute
  '/Countries/New-Zealand': typeof CountriesNewZealandRoute
  '/Countries/Oman': typeof CountriesOmanRoute
  '/Countries/Qatar': typeof CountriesQatarRoute
  '/Countries/Russia': typeof CountriesRussiaRoute
  '/Countries/SaudiArabia': typeof CountriesSaudiArabiaRoute
  '/Countries/Singapore': typeof CountriesSingaporeRoute
  '/Countries/UAE': typeof CountriesUAERoute
  '/Countries/UK': typeof CountriesUKRoute
  '/Employer/applications': typeof EmployerApplicationsRoute
  '/Employer/candidate': typeof EmployerCandidateRoute
  '/Employer/dashboard': typeof EmployerDashboardRoute
  '/Employer/employer': typeof EmployerEmployerRoute
  '/Employer/jobs': typeof EmployerJobsRoute
  '/Employer/my-company': typeof EmployerMyCompanyRoute
  '/Employer/requirements': typeof EmployerRequirementsRoute
  '/Employer/settings': typeof EmployerSettingsRoute
  '/Services/Doctors': typeof ServicesDoctorsRoute
  '/Services/Documentation': typeof ServicesDocumentationRoute
  '/Services/Grooming': typeof ServicesGroomingRoute
  '/Services/Healthcare-rec': typeof ServicesHealthcareRecRoute
  '/Services/Mock-Interviews': typeof ServicesMockInterviewsRoute
  '/Services/Nurses': typeof ServicesNursesRoute
  '/Services/Nursing-rec': typeof ServicesNursingRecRoute
  '/Services/ParaMedical-tech': typeof ServicesParaMedicalTechRoute
  '/Services/Prometric-coaching': typeof ServicesPrometricCoachingRoute
  '/Services/Technical-rec': typeof ServicesTechnicalRecRoute
  '/Services/Training': typeof ServicesTrainingRoute
  '/Services/Visa': typeof ServicesVisaRoute
  '/Services/': typeof ServicesIndexRoute
  '/Admin/application/$id': typeof AdminApplicationIdRoute
  '/Admin/candidate/$id': typeof AdminCandidateIdRoute
  '/Admin/employer/$id': typeof AdminEmployerIdRoute
  '/Admin/job/$id': typeof AdminJobIdRoute
  '/Candidates/applications/$id': typeof CandidatesApplicationsIdRoute
  '/Candidates/jobs/$id': typeof CandidatesJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Home'
    | '/about'
    | '/contact'
    | '/countries'
    | '/employers'
    | '/privacypolicy'
    | '/Admin/applications'
    | '/Admin/candidates'
    | '/Admin/countries'
    | '/Admin/dashboard'
    | '/Admin/employer'
    | '/Admin/jobs'
    | '/Admin/requirements'
    | '/Admin/settings'
    | '/Candidates/applications'
    | '/Candidates/candidate'
    | '/Candidates/dashboard'
    | '/Candidates/jobs'
    | '/Candidates/notifications'
    | '/Candidates/profile'
    | '/Candidates/resume'
    | '/Candidates/saved-jobs'
    | '/Countries/Australia'
    | '/Countries/Canada'
    | '/Countries/Denmark'
    | '/Countries/Germany'
    | '/Countries/Ireland'
    | '/Countries/Kuwait'
    | '/Countries/Malaysia'
    | '/Countries/Malta'
    | '/Countries/New-Zealand'
    | '/Countries/Oman'
    | '/Countries/Qatar'
    | '/Countries/Russia'
    | '/Countries/SaudiArabia'
    | '/Countries/Singapore'
    | '/Countries/UAE'
    | '/Countries/UK'
    | '/Employer/applications'
    | '/Employer/candidate'
    | '/Employer/dashboard'
    | '/Employer/employer'
    | '/Employer/jobs'
    | '/Employer/my-company'
    | '/Employer/requirements'
    | '/Employer/settings'
    | '/Services/Doctors'
    | '/Services/Documentation'
    | '/Services/Grooming'
    | '/Services/Healthcare-rec'
    | '/Services/Mock-Interviews'
    | '/Services/Nurses'
    | '/Services/Nursing-rec'
    | '/Services/ParaMedical-tech'
    | '/Services/Prometric-coaching'
    | '/Services/Technical-rec'
    | '/Services/Training'
    | '/Services/Visa'
    | '/Services/'
    | '/Admin/application/$id'
    | '/Admin/candidate/$id'
    | '/Admin/employer/$id'
    | '/Admin/job/$id'
    | '/Candidates/applications/$id'
    | '/Candidates/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Home'
    | '/about'
    | '/contact'
    | '/countries'
    | '/employers'
    | '/privacypolicy'
    | '/Admin/applications'
    | '/Admin/candidates'
    | '/Admin/countries'
    | '/Admin/dashboard'
    | '/Admin/employer'
    | '/Admin/jobs'
    | '/Admin/requirements'
    | '/Admin/settings'
    | '/Candidates/applications'
    | '/Candidates/candidate'
    | '/Candidates/dashboard'
    | '/Candidates/jobs'
    | '/Candidates/notifications'
    | '/Candidates/profile'
    | '/Candidates/resume'
    | '/Candidates/saved-jobs'
    | '/Countries/Australia'
    | '/Countries/Canada'
    | '/Countries/Denmark'
    | '/Countries/Germany'
    | '/Countries/Ireland'
    | '/Countries/Kuwait'
    | '/Countries/Malaysia'
    | '/Countries/Malta'
    | '/Countries/New-Zealand'
    | '/Countries/Oman'
    | '/Countries/Qatar'
    | '/Countries/Russia'
    | '/Countries/SaudiArabia'
    | '/Countries/Singapore'
    | '/Countries/UAE'
    | '/Countries/UK'
    | '/Employer/applications'
    | '/Employer/candidate'
    | '/Employer/dashboard'
    | '/Employer/employer'
    | '/Employer/jobs'
    | '/Employer/my-company'
    | '/Employer/requirements'
    | '/Employer/settings'
    | '/Services/Doctors'
    | '/Services/Documentation'
    | '/Services/Grooming'
    | '/Services/Healthcare-rec'
    | '/Services/Mock-Interviews'
    | '/Services/Nurses'
    | '/Services/Nursing-rec'
    | '/Services/ParaMedical-tech'
    | '/Services/Prometric-coaching'
    | '/Services/Technical-rec'
    | '/Services/Training'
    | '/Services/Visa'
    | '/Services'
    | '/Admin/application/$id'
    | '/Admin/candidate/$id'
    | '/Admin/employer/$id'
    | '/Admin/job/$id'
    | '/Candidates/applications/$id'
    | '/Candidates/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/Home'
    | '/about'
    | '/contact'
    | '/countries'
    | '/employers'
    | '/privacypolicy'
    | '/Admin/applications'
    | '/Admin/candidates'
    | '/Admin/countries'
    | '/Admin/dashboard'
    | '/Admin/employer'
    | '/Admin/jobs'
    | '/Admin/requirements'
    | '/Admin/settings'
    | '/Candidates/applications'
    | '/Candidates/candidate'
    | '/Candidates/dashboard'
    | '/Candidates/jobs'
    | '/Candidates/notifications'
    | '/Candidates/profile'
    | '/Candidates/resume'
    | '/Candidates/saved-jobs'
    | '/Countries/Australia'
    | '/Countries/Canada'
    | '/Countries/Denmark'
    | '/Countries/Germany'
    | '/Countries/Ireland'
    | '/Countries/Kuwait'
    | '/Countries/Malaysia'
    | '/Countries/Malta'
    | '/Countries/New-Zealand'
    | '/Countries/Oman'
    | '/Countries/Qatar'
    | '/Countries/Russia'
    | '/Countries/SaudiArabia'
    | '/Countries/Singapore'
    | '/Countries/UAE'
    | '/Countries/UK'
    | '/Employer/applications'
    | '/Employer/candidate'
    | '/Employer/dashboard'
    | '/Employer/employer'
    | '/Employer/jobs'
    | '/Employer/my-company'
    | '/Employer/requirements'
    | '/Employer/settings'
    | '/Services/Doctors'
    | '/Services/Documentation'
    | '/Services/Grooming'
    | '/Services/Healthcare-rec'
    | '/Services/Mock-Interviews'
    | '/Services/Nurses'
    | '/Services/Nursing-rec'
    | '/Services/ParaMedical-tech'
    | '/Services/Prometric-coaching'
    | '/Services/Technical-rec'
    | '/Services/Training'
    | '/Services/Visa'
    | '/Services/'
    | '/Admin/application/$id'
    | '/Admin/candidate/$id'
    | '/Admin/employer/$id'
    | '/Admin/job/$id'
    | '/Candidates/applications/$id'
    | '/Candidates/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  EmployersRoute: typeof EmployersRoute
  PrivacypolicyRoute: typeof PrivacypolicyRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCountriesRoute: typeof AdminCountriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployerRoute: typeof AdminEmployerRouteWithChildren
  AdminJobsRoute: typeof AdminJobsRoute
  AdminRequirementsRoute: typeof AdminRequirementsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CandidatesApplicationsRoute: typeof CandidatesApplicationsRouteWithChildren
  CandidatesCandidateRoute: typeof CandidatesCandidateRoute
  CandidatesDashboardRoute: typeof CandidatesDashboardRoute
  CandidatesJobsRoute: typeof CandidatesJobsRouteWithChildren
  CandidatesNotificationsRoute: typeof CandidatesNotificationsRoute
  CandidatesProfileRoute: typeof CandidatesProfileRoute
  CandidatesResumeRoute: typeof CandidatesResumeRoute
  CandidatesSavedJobsRoute: typeof CandidatesSavedJobsRoute
  CountriesAustraliaRoute: typeof CountriesAustraliaRoute
  CountriesCanadaRoute: typeof CountriesCanadaRoute
  CountriesDenmarkRoute: typeof CountriesDenmarkRoute
  CountriesGermanyRoute: typeof CountriesGermanyRoute
  CountriesIrelandRoute: typeof CountriesIrelandRoute
  CountriesKuwaitRoute: typeof CountriesKuwaitRoute
  CountriesMalaysiaRoute: typeof CountriesMalaysiaRoute
  CountriesMaltaRoute: typeof CountriesMaltaRoute
  CountriesNewZealandRoute: typeof CountriesNewZealandRoute
  CountriesOmanRoute: typeof CountriesOmanRoute
  CountriesQatarRoute: typeof CountriesQatarRoute
  CountriesRussiaRoute: typeof CountriesRussiaRoute
  CountriesSaudiArabiaRoute: typeof CountriesSaudiArabiaRoute
  CountriesSingaporeRoute: typeof CountriesSingaporeRoute
  CountriesUAERoute: typeof CountriesUAERoute
  CountriesUKRoute: typeof CountriesUKRoute
  EmployerApplicationsRoute: typeof EmployerApplicationsRoute
  EmployerCandidateRoute: typeof EmployerCandidateRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerEmployerRoute: typeof EmployerEmployerRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  EmployerMyCompanyRoute: typeof EmployerMyCompanyRoute
  EmployerRequirementsRoute: typeof EmployerRequirementsRoute
  EmployerSettingsRoute: typeof EmployerSettingsRoute
  ServicesDoctorsRoute: typeof ServicesDoctorsRoute
  ServicesDocumentationRoute: typeof ServicesDocumentationRoute
  ServicesGroomingRoute: typeof ServicesGroomingRoute
  ServicesHealthcareRecRoute: typeof ServicesHealthcareRecRoute
  ServicesMockInterviewsRoute: typeof ServicesMockInterviewsRoute
  ServicesNursesRoute: typeof ServicesNursesRoute
  ServicesNursingRecRoute: typeof ServicesNursingRecRoute
  ServicesParaMedicalTechRoute: typeof ServicesParaMedicalTechRoute
  ServicesPrometricCoachingRoute: typeof ServicesPrometricCoachingRoute
  ServicesTechnicalRecRoute: typeof ServicesTechnicalRecRoute
  ServicesTrainingRoute: typeof ServicesTrainingRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  AdminApplicationIdRoute: typeof AdminApplicationIdRoute
  AdminCandidateIdRoute: typeof AdminCandidateIdRoute
  AdminJobIdRoute: typeof AdminJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacypolicy': {
      id: '/privacypolicy'
      path: '/privacypolicy'
      fullPath: '/privacypolicy'
      preLoaderRoute: typeof PrivacypolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/': {
      id: '/Services/'
      path: '/Services'
      fullPath: '/Services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Visa': {
      id: '/Services/Visa'
      path: '/Services/Visa'
      fullPath: '/Services/Visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Training': {
      id: '/Services/Training'
      path: '/Services/Training'
      fullPath: '/Services/Training'
      preLoaderRoute: typeof ServicesTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Technical-rec': {
      id: '/Services/Technical-rec'
      path: '/Services/Technical-rec'
      fullPath: '/Services/Technical-rec'
      preLoaderRoute: typeof ServicesTechnicalRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Prometric-coaching': {
      id: '/Services/Prometric-coaching'
      path: '/Services/Prometric-coaching'
      fullPath: '/Services/Prometric-coaching'
      preLoaderRoute: typeof ServicesPrometricCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/ParaMedical-tech': {
      id: '/Services/ParaMedical-tech'
      path: '/Services/ParaMedical-tech'
      fullPath: '/Services/ParaMedical-tech'
      preLoaderRoute: typeof ServicesParaMedicalTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Nursing-rec': {
      id: '/Services/Nursing-rec'
      path: '/Services/Nursing-rec'
      fullPath: '/Services/Nursing-rec'
      preLoaderRoute: typeof ServicesNursingRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Nurses': {
      id: '/Services/Nurses'
      path: '/Services/Nurses'
      fullPath: '/Services/Nurses'
      preLoaderRoute: typeof ServicesNursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Mock-Interviews': {
      id: '/Services/Mock-Interviews'
      path: '/Services/Mock-Interviews'
      fullPath: '/Services/Mock-Interviews'
      preLoaderRoute: typeof ServicesMockInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Healthcare-rec': {
      id: '/Services/Healthcare-rec'
      path: '/Services/Healthcare-rec'
      fullPath: '/Services/Healthcare-rec'
      preLoaderRoute: typeof ServicesHealthcareRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Grooming': {
      id: '/Services/Grooming'
      path: '/Services/Grooming'
      fullPath: '/Services/Grooming'
      preLoaderRoute: typeof ServicesGroomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Documentation': {
      id: '/Services/Documentation'
      path: '/Services/Documentation'
      fullPath: '/Services/Documentation'
      preLoaderRoute: typeof ServicesDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Doctors': {
      id: '/Services/Doctors'
      path: '/Services/Doctors'
      fullPath: '/Services/Doctors'
      preLoaderRoute: typeof ServicesDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/settings': {
      id: '/Employer/settings'
      path: '/Employer/settings'
      fullPath: '/Employer/settings'
      preLoaderRoute: typeof EmployerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/requirements': {
      id: '/Employer/requirements'
      path: '/Employer/requirements'
      fullPath: '/Employer/requirements'
      preLoaderRoute: typeof EmployerRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/my-company': {
      id: '/Employer/my-company'
      path: '/Employer/my-company'
      fullPath: '/Employer/my-company'
      preLoaderRoute: typeof EmployerMyCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/jobs': {
      id: '/Employer/jobs'
      path: '/Employer/jobs'
      fullPath: '/Employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/employer': {
      id: '/Employer/employer'
      path: '/Employer/employer'
      fullPath: '/Employer/employer'
      preLoaderRoute: typeof EmployerEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/dashboard': {
      id: '/Employer/dashboard'
      path: '/Employer/dashboard'
      fullPath: '/Employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/candidate': {
      id: '/Employer/candidate'
      path: '/Employer/candidate'
      fullPath: '/Employer/candidate'
      preLoaderRoute: typeof EmployerCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Employer/applications': {
      id: '/Employer/applications'
      path: '/Employer/applications'
      fullPath: '/Employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/UK': {
      id: '/Countries/UK'
      path: '/Countries/UK'
      fullPath: '/Countries/UK'
      preLoaderRoute: typeof CountriesUKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/UAE': {
      id: '/Countries/UAE'
      path: '/Countries/UAE'
      fullPath: '/Countries/UAE'
      preLoaderRoute: typeof CountriesUAERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Singapore': {
      id: '/Countries/Singapore'
      path: '/Countries/Singapore'
      fullPath: '/Countries/Singapore'
      preLoaderRoute: typeof CountriesSingaporeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/SaudiArabia': {
      id: '/Countries/SaudiArabia'
      path: '/Countries/SaudiArabia'
      fullPath: '/Countries/SaudiArabia'
      preLoaderRoute: typeof CountriesSaudiArabiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Russia': {
      id: '/Countries/Russia'
      path: '/Countries/Russia'
      fullPath: '/Countries/Russia'
      preLoaderRoute: typeof CountriesRussiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Qatar': {
      id: '/Countries/Qatar'
      path: '/Countries/Qatar'
      fullPath: '/Countries/Qatar'
      preLoaderRoute: typeof CountriesQatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Oman': {
      id: '/Countries/Oman'
      path: '/Countries/Oman'
      fullPath: '/Countries/Oman'
      preLoaderRoute: typeof CountriesOmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/New-Zealand': {
      id: '/Countries/New-Zealand'
      path: '/Countries/New-Zealand'
      fullPath: '/Countries/New-Zealand'
      preLoaderRoute: typeof CountriesNewZealandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Malta': {
      id: '/Countries/Malta'
      path: '/Countries/Malta'
      fullPath: '/Countries/Malta'
      preLoaderRoute: typeof CountriesMaltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Malaysia': {
      id: '/Countries/Malaysia'
      path: '/Countries/Malaysia'
      fullPath: '/Countries/Malaysia'
      preLoaderRoute: typeof CountriesMalaysiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Kuwait': {
      id: '/Countries/Kuwait'
      path: '/Countries/Kuwait'
      fullPath: '/Countries/Kuwait'
      preLoaderRoute: typeof CountriesKuwaitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Ireland': {
      id: '/Countries/Ireland'
      path: '/Countries/Ireland'
      fullPath: '/Countries/Ireland'
      preLoaderRoute: typeof CountriesIrelandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Germany': {
      id: '/Countries/Germany'
      path: '/Countries/Germany'
      fullPath: '/Countries/Germany'
      preLoaderRoute: typeof CountriesGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Denmark': {
      id: '/Countries/Denmark'
      path: '/Countries/Denmark'
      fullPath: '/Countries/Denmark'
      preLoaderRoute: typeof CountriesDenmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Canada': {
      id: '/Countries/Canada'
      path: '/Countries/Canada'
      fullPath: '/Countries/Canada'
      preLoaderRoute: typeof CountriesCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Countries/Australia': {
      id: '/Countries/Australia'
      path: '/Countries/Australia'
      fullPath: '/Countries/Australia'
      preLoaderRoute: typeof CountriesAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/saved-jobs': {
      id: '/Candidates/saved-jobs'
      path: '/Candidates/saved-jobs'
      fullPath: '/Candidates/saved-jobs'
      preLoaderRoute: typeof CandidatesSavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/resume': {
      id: '/Candidates/resume'
      path: '/Candidates/resume'
      fullPath: '/Candidates/resume'
      preLoaderRoute: typeof CandidatesResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/profile': {
      id: '/Candidates/profile'
      path: '/Candidates/profile'
      fullPath: '/Candidates/profile'
      preLoaderRoute: typeof CandidatesProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/notifications': {
      id: '/Candidates/notifications'
      path: '/Candidates/notifications'
      fullPath: '/Candidates/notifications'
      preLoaderRoute: typeof CandidatesNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/jobs': {
      id: '/Candidates/jobs'
      path: '/Candidates/jobs'
      fullPath: '/Candidates/jobs'
      preLoaderRoute: typeof CandidatesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/dashboard': {
      id: '/Candidates/dashboard'
      path: '/Candidates/dashboard'
      fullPath: '/Candidates/dashboard'
      preLoaderRoute: typeof CandidatesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/candidate': {
      id: '/Candidates/candidate'
      path: '/Candidates/candidate'
      fullPath: '/Candidates/candidate'
      preLoaderRoute: typeof CandidatesCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/applications': {
      id: '/Candidates/applications'
      path: '/Candidates/applications'
      fullPath: '/Candidates/applications'
      preLoaderRoute: typeof CandidatesApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/settings': {
      id: '/Admin/settings'
      path: '/Admin/settings'
      fullPath: '/Admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/requirements': {
      id: '/Admin/requirements'
      path: '/Admin/requirements'
      fullPath: '/Admin/requirements'
      preLoaderRoute: typeof AdminRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/jobs': {
      id: '/Admin/jobs'
      path: '/Admin/jobs'
      fullPath: '/Admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/employer': {
      id: '/Admin/employer'
      path: '/Admin/employer'
      fullPath: '/Admin/employer'
      preLoaderRoute: typeof AdminEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/dashboard': {
      id: '/Admin/dashboard'
      path: '/Admin/dashboard'
      fullPath: '/Admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/countries': {
      id: '/Admin/countries'
      path: '/Admin/countries'
      fullPath: '/Admin/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/candidates': {
      id: '/Admin/candidates'
      path: '/Admin/candidates'
      fullPath: '/Admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/applications': {
      id: '/Admin/applications'
      path: '/Admin/applications'
      fullPath: '/Admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/jobs/$id': {
      id: '/Candidates/jobs/$id'
      path: '/$id'
      fullPath: '/Candidates/jobs/$id'
      preLoaderRoute: typeof CandidatesJobsIdRouteImport
      parentRoute: typeof CandidatesJobsRoute
    }
    '/Candidates/applications/$id': {
      id: '/Candidates/applications/$id'
      path: '/$id'
      fullPath: '/Candidates/applications/$id'
      preLoaderRoute: typeof CandidatesApplicationsIdRouteImport
      parentRoute: typeof CandidatesApplicationsRoute
    }
    '/Admin/job/$id': {
      id: '/Admin/job/$id'
      path: '/Admin/job/$id'
      fullPath: '/Admin/job/$id'
      preLoaderRoute: typeof AdminJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/employer/$id': {
      id: '/Admin/employer/$id'
      path: '/$id'
      fullPath: '/Admin/employer/$id'
      preLoaderRoute: typeof AdminEmployerIdRouteImport
      parentRoute: typeof AdminEmployerRoute
    }
    '/Admin/candidate/$id': {
      id: '/Admin/candidate/$id'
      path: '/Admin/candidate/$id'
      fullPath: '/Admin/candidate/$id'
      preLoaderRoute: typeof AdminCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin/application/$id': {
      id: '/Admin/application/$id'
      path: '/Admin/application/$id'
      fullPath: '/Admin/application/$id'
      preLoaderRoute: typeof AdminApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminEmployerRouteChildren {
  AdminEmployerIdRoute: typeof AdminEmployerIdRoute
}

const AdminEmployerRouteChildren: AdminEmployerRouteChildren = {
  AdminEmployerIdRoute: AdminEmployerIdRoute,
}

const AdminEmployerRouteWithChildren = AdminEmployerRoute._addFileChildren(
  AdminEmployerRouteChildren,
)

interface CandidatesApplicationsRouteChildren {
  CandidatesApplicationsIdRoute: typeof CandidatesApplicationsIdRoute
}

const CandidatesApplicationsRouteChildren: CandidatesApplicationsRouteChildren =
  {
    CandidatesApplicationsIdRoute: CandidatesApplicationsIdRoute,
  }

const CandidatesApplicationsRouteWithChildren =
  CandidatesApplicationsRoute._addFileChildren(
    CandidatesApplicationsRouteChildren,
  )

interface CandidatesJobsRouteChildren {
  CandidatesJobsIdRoute: typeof CandidatesJobsIdRoute
}

const CandidatesJobsRouteChildren: CandidatesJobsRouteChildren = {
  CandidatesJobsIdRoute: CandidatesJobsIdRoute,
}

const CandidatesJobsRouteWithChildren = CandidatesJobsRoute._addFileChildren(
  CandidatesJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  EmployersRoute: EmployersRoute,
  PrivacypolicyRoute: PrivacypolicyRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCountriesRoute: AdminCountriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployerRoute: AdminEmployerRouteWithChildren,
  AdminJobsRoute: AdminJobsRoute,
  AdminRequirementsRoute: AdminRequirementsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CandidatesApplicationsRoute: CandidatesApplicationsRouteWithChildren,
  CandidatesCandidateRoute: CandidatesCandidateRoute,
  CandidatesDashboardRoute: CandidatesDashboardRoute,
  CandidatesJobsRoute: CandidatesJobsRouteWithChildren,
  CandidatesNotificationsRoute: CandidatesNotificationsRoute,
  CandidatesProfileRoute: CandidatesProfileRoute,
  CandidatesResumeRoute: CandidatesResumeRoute,
  CandidatesSavedJobsRoute: CandidatesSavedJobsRoute,
  CountriesAustraliaRoute: CountriesAustraliaRoute,
  CountriesCanadaRoute: CountriesCanadaRoute,
  CountriesDenmarkRoute: CountriesDenmarkRoute,
  CountriesGermanyRoute: CountriesGermanyRoute,
  CountriesIrelandRoute: CountriesIrelandRoute,
  CountriesKuwaitRoute: CountriesKuwaitRoute,
  CountriesMalaysiaRoute: CountriesMalaysiaRoute,
  CountriesMaltaRoute: CountriesMaltaRoute,
  CountriesNewZealandRoute: CountriesNewZealandRoute,
  CountriesOmanRoute: CountriesOmanRoute,
  CountriesQatarRoute: CountriesQatarRoute,
  CountriesRussiaRoute: CountriesRussiaRoute,
  CountriesSaudiArabiaRoute: CountriesSaudiArabiaRoute,
  CountriesSingaporeRoute: CountriesSingaporeRoute,
  CountriesUAERoute: CountriesUAERoute,
  CountriesUKRoute: CountriesUKRoute,
  EmployerApplicationsRoute: EmployerApplicationsRoute,
  EmployerCandidateRoute: EmployerCandidateRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerEmployerRoute: EmployerEmployerRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  EmployerMyCompanyRoute: EmployerMyCompanyRoute,
  EmployerRequirementsRoute: EmployerRequirementsRoute,
  EmployerSettingsRoute: EmployerSettingsRoute,
  ServicesDoctorsRoute: ServicesDoctorsRoute,
  ServicesDocumentationRoute: ServicesDocumentationRoute,
  ServicesGroomingRoute: ServicesGroomingRoute,
  ServicesHealthcareRecRoute: ServicesHealthcareRecRoute,
  ServicesMockInterviewsRoute: ServicesMockInterviewsRoute,
  ServicesNursesRoute: ServicesNursesRoute,
  ServicesNursingRecRoute: ServicesNursingRecRoute,
  ServicesParaMedicalTechRoute: ServicesParaMedicalTechRoute,
  ServicesPrometricCoachingRoute: ServicesPrometricCoachingRoute,
  ServicesTechnicalRecRoute: ServicesTechnicalRecRoute,
  ServicesTrainingRoute: ServicesTrainingRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  AdminApplicationIdRoute: AdminApplicationIdRoute,
  AdminCandidateIdRoute: AdminCandidateIdRoute,
  AdminJobIdRoute: AdminJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
