/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacypolicyRouteImport } from './routes/privacypolicy'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/Services/index'
import { Route as ServicesVisaRouteImport } from './routes/Services/Visa'
import { Route as ServicesTrainingRouteImport } from './routes/Services/Training'
import { Route as ServicesTechnicalRecRouteImport } from './routes/Services/Technical-rec'
import { Route as ServicesPrometricCoachingRouteImport } from './routes/Services/Prometric-coaching'
import { Route as ServicesParaMedicalTechRouteImport } from './routes/Services/ParaMedical-tech'
import { Route as ServicesNursingRecRouteImport } from './routes/Services/Nursing-rec'
import { Route as ServicesNursesRouteImport } from './routes/Services/Nurses'
import { Route as ServicesMockInterviewsRouteImport } from './routes/Services/Mock-Interviews'
import { Route as ServicesHealthcareRecRouteImport } from './routes/Services/Healthcare-rec'
import { Route as ServicesGroomingRouteImport } from './routes/Services/Grooming'
import { Route as ServicesDocumentationRouteImport } from './routes/Services/Documentation'
import { Route as ServicesDoctorsRouteImport } from './routes/Services/Doctors'
import { Route as CandidatesVisaRouteImport } from './routes/Candidates/visa'
import { Route as CandidatesProfileRouteImport } from './routes/Candidates/profile'
import { Route as CandidatesOffersRouteImport } from './routes/Candidates/offers'
import { Route as CandidatesNotificationsRouteImport } from './routes/Candidates/notifications'
import { Route as CandidatesMedicalRouteImport } from './routes/Candidates/medical'
import { Route as CandidatesJobsRouteImport } from './routes/Candidates/jobs'
import { Route as CandidatesInterviewsRouteImport } from './routes/Candidates/interviews'
import { Route as CandidatesDocumentsRouteImport } from './routes/Candidates/documents'
import { Route as CandidatesDeploymentRouteImport } from './routes/Candidates/deployment'
import { Route as CandidatesDashboardRouteImport } from './routes/Candidates/dashboard'
import { Route as CandidatesApplicationsRouteImport } from './routes/Candidates/applications'
import { Route as CandidatesJobsIdRouteImport } from './routes/Candidates/jobs.$id'
import { Route as CandidatesApplicationsIdRouteImport } from './routes/Candidates/applications.$id'

const PrivacypolicyRoute = PrivacypolicyRouteImport.update({
  id: '/privacypolicy',
  path: '/privacypolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/Services/',
  path: '/Services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/Services/Visa',
  path: '/Services/Visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrainingRoute = ServicesTrainingRouteImport.update({
  id: '/Services/Training',
  path: '/Services/Training',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTechnicalRecRoute = ServicesTechnicalRecRouteImport.update({
  id: '/Services/Technical-rec',
  path: '/Services/Technical-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrometricCoachingRoute =
  ServicesPrometricCoachingRouteImport.update({
    id: '/Services/Prometric-coaching',
    path: '/Services/Prometric-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesParaMedicalTechRoute = ServicesParaMedicalTechRouteImport.update({
  id: '/Services/ParaMedical-tech',
  path: '/Services/ParaMedical-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNursingRecRoute = ServicesNursingRecRouteImport.update({
  id: '/Services/Nursing-rec',
  path: '/Services/Nursing-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNursesRoute = ServicesNursesRouteImport.update({
  id: '/Services/Nurses',
  path: '/Services/Nurses',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMockInterviewsRoute = ServicesMockInterviewsRouteImport.update({
  id: '/Services/Mock-Interviews',
  path: '/Services/Mock-Interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHealthcareRecRoute = ServicesHealthcareRecRouteImport.update({
  id: '/Services/Healthcare-rec',
  path: '/Services/Healthcare-rec',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGroomingRoute = ServicesGroomingRouteImport.update({
  id: '/Services/Grooming',
  path: '/Services/Grooming',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDocumentationRoute = ServicesDocumentationRouteImport.update({
  id: '/Services/Documentation',
  path: '/Services/Documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDoctorsRoute = ServicesDoctorsRouteImport.update({
  id: '/Services/Doctors',
  path: '/Services/Doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesVisaRoute = CandidatesVisaRouteImport.update({
  id: '/Candidates/visa',
  path: '/Candidates/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesProfileRoute = CandidatesProfileRouteImport.update({
  id: '/Candidates/profile',
  path: '/Candidates/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesOffersRoute = CandidatesOffersRouteImport.update({
  id: '/Candidates/offers',
  path: '/Candidates/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesNotificationsRoute = CandidatesNotificationsRouteImport.update({
  id: '/Candidates/notifications',
  path: '/Candidates/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesMedicalRoute = CandidatesMedicalRouteImport.update({
  id: '/Candidates/medical',
  path: '/Candidates/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesJobsRoute = CandidatesJobsRouteImport.update({
  id: '/Candidates/jobs',
  path: '/Candidates/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesInterviewsRoute = CandidatesInterviewsRouteImport.update({
  id: '/Candidates/interviews',
  path: '/Candidates/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesDocumentsRoute = CandidatesDocumentsRouteImport.update({
  id: '/Candidates/documents',
  path: '/Candidates/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesDeploymentRoute = CandidatesDeploymentRouteImport.update({
  id: '/Candidates/deployment',
  path: '/Candidates/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesDashboardRoute = CandidatesDashboardRouteImport.update({
  id: '/Candidates/dashboard',
  path: '/Candidates/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesApplicationsRoute = CandidatesApplicationsRouteImport.update({
  id: '/Candidates/applications',
  path: '/Candidates/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesJobsIdRoute = CandidatesJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidatesJobsRoute,
} as any)
const CandidatesApplicationsIdRoute =
  CandidatesApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => CandidatesApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/Candidates/applications': typeof CandidatesApplicationsRouteWithChildren
  '/Candidates/dashboard': typeof CandidatesDashboardRoute
  '/Candidates/deployment': typeof CandidatesDeploymentRoute
  '/Candidates/documents': typeof CandidatesDocumentsRoute
  '/Candidates/interviews': typeof CandidatesInterviewsRoute
  '/Candidates/jobs': typeof CandidatesJobsRouteWithChildren
  '/Candidates/medical': typeof CandidatesMedicalRoute
  '/Candidates/notifications': typeof CandidatesNotificationsRoute
  '/Candidates/offers': typeof CandidatesOffersRoute
  '/Candidates/profile': typeof CandidatesProfileRoute
  '/Candidates/visa': typeof CandidatesVisaRoute
  '/Services/Doctors': typeof ServicesDoctorsRoute
  '/Services/Documentation': typeof ServicesDocumentationRoute
  '/Services/Grooming': typeof ServicesGroomingRoute
  '/Services/Healthcare-rec': typeof ServicesHealthcareRecRoute
  '/Services/Mock-Interviews': typeof ServicesMockInterviewsRoute
  '/Services/Nurses': typeof ServicesNursesRoute
  '/Services/Nursing-rec': typeof ServicesNursingRecRoute
  '/Services/ParaMedical-tech': typeof ServicesParaMedicalTechRoute
  '/Services/Prometric-coaching': typeof ServicesPrometricCoachingRoute
  '/Services/Technical-rec': typeof ServicesTechnicalRecRoute
  '/Services/Training': typeof ServicesTrainingRoute
  '/Services/Visa': typeof ServicesVisaRoute
  '/Services/': typeof ServicesIndexRoute
  '/Candidates/applications/$id': typeof CandidatesApplicationsIdRoute
  '/Candidates/jobs/$id': typeof CandidatesJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/Candidates/applications': typeof CandidatesApplicationsRouteWithChildren
  '/Candidates/dashboard': typeof CandidatesDashboardRoute
  '/Candidates/deployment': typeof CandidatesDeploymentRoute
  '/Candidates/documents': typeof CandidatesDocumentsRoute
  '/Candidates/interviews': typeof CandidatesInterviewsRoute
  '/Candidates/jobs': typeof CandidatesJobsRouteWithChildren
  '/Candidates/medical': typeof CandidatesMedicalRoute
  '/Candidates/notifications': typeof CandidatesNotificationsRoute
  '/Candidates/offers': typeof CandidatesOffersRoute
  '/Candidates/profile': typeof CandidatesProfileRoute
  '/Candidates/visa': typeof CandidatesVisaRoute
  '/Services/Doctors': typeof ServicesDoctorsRoute
  '/Services/Documentation': typeof ServicesDocumentationRoute
  '/Services/Grooming': typeof ServicesGroomingRoute
  '/Services/Healthcare-rec': typeof ServicesHealthcareRecRoute
  '/Services/Mock-Interviews': typeof ServicesMockInterviewsRoute
  '/Services/Nurses': typeof ServicesNursesRoute
  '/Services/Nursing-rec': typeof ServicesNursingRecRoute
  '/Services/ParaMedical-tech': typeof ServicesParaMedicalTechRoute
  '/Services/Prometric-coaching': typeof ServicesPrometricCoachingRoute
  '/Services/Technical-rec': typeof ServicesTechnicalRecRoute
  '/Services/Training': typeof ServicesTrainingRoute
  '/Services/Visa': typeof ServicesVisaRoute
  '/Services': typeof ServicesIndexRoute
  '/Candidates/applications/$id': typeof CandidatesApplicationsIdRoute
  '/Candidates/jobs/$id': typeof CandidatesJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Home': typeof HomeRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/privacypolicy': typeof PrivacypolicyRoute
  '/Candidates/applications': typeof CandidatesApplicationsRouteWithChildren
  '/Candidates/dashboard': typeof CandidatesDashboardRoute
  '/Candidates/deployment': typeof CandidatesDeploymentRoute
  '/Candidates/documents': typeof CandidatesDocumentsRoute
  '/Candidates/interviews': typeof CandidatesInterviewsRoute
  '/Candidates/jobs': typeof CandidatesJobsRouteWithChildren
  '/Candidates/medical': typeof CandidatesMedicalRoute
  '/Candidates/notifications': typeof CandidatesNotificationsRoute
  '/Candidates/offers': typeof CandidatesOffersRoute
  '/Candidates/profile': typeof CandidatesProfileRoute
  '/Candidates/visa': typeof CandidatesVisaRoute
  '/Services/Doctors': typeof ServicesDoctorsRoute
  '/Services/Documentation': typeof ServicesDocumentationRoute
  '/Services/Grooming': typeof ServicesGroomingRoute
  '/Services/Healthcare-rec': typeof ServicesHealthcareRecRoute
  '/Services/Mock-Interviews': typeof ServicesMockInterviewsRoute
  '/Services/Nurses': typeof ServicesNursesRoute
  '/Services/Nursing-rec': typeof ServicesNursingRecRoute
  '/Services/ParaMedical-tech': typeof ServicesParaMedicalTechRoute
  '/Services/Prometric-coaching': typeof ServicesPrometricCoachingRoute
  '/Services/Technical-rec': typeof ServicesTechnicalRecRoute
  '/Services/Training': typeof ServicesTrainingRoute
  '/Services/Visa': typeof ServicesVisaRoute
  '/Services/': typeof ServicesIndexRoute
  '/Candidates/applications/$id': typeof CandidatesApplicationsIdRoute
  '/Candidates/jobs/$id': typeof CandidatesJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Home'
    | '/about'
    | '/contact'
    | '/employers'
    | '/privacypolicy'
    | '/Candidates/applications'
    | '/Candidates/dashboard'
    | '/Candidates/deployment'
    | '/Candidates/documents'
    | '/Candidates/interviews'
    | '/Candidates/jobs'
    | '/Candidates/medical'
    | '/Candidates/notifications'
    | '/Candidates/offers'
    | '/Candidates/profile'
    | '/Candidates/visa'
    | '/Services/Doctors'
    | '/Services/Documentation'
    | '/Services/Grooming'
    | '/Services/Healthcare-rec'
    | '/Services/Mock-Interviews'
    | '/Services/Nurses'
    | '/Services/Nursing-rec'
    | '/Services/ParaMedical-tech'
    | '/Services/Prometric-coaching'
    | '/Services/Technical-rec'
    | '/Services/Training'
    | '/Services/Visa'
    | '/Services/'
    | '/Candidates/applications/$id'
    | '/Candidates/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Home'
    | '/about'
    | '/contact'
    | '/employers'
    | '/privacypolicy'
    | '/Candidates/applications'
    | '/Candidates/dashboard'
    | '/Candidates/deployment'
    | '/Candidates/documents'
    | '/Candidates/interviews'
    | '/Candidates/jobs'
    | '/Candidates/medical'
    | '/Candidates/notifications'
    | '/Candidates/offers'
    | '/Candidates/profile'
    | '/Candidates/visa'
    | '/Services/Doctors'
    | '/Services/Documentation'
    | '/Services/Grooming'
    | '/Services/Healthcare-rec'
    | '/Services/Mock-Interviews'
    | '/Services/Nurses'
    | '/Services/Nursing-rec'
    | '/Services/ParaMedical-tech'
    | '/Services/Prometric-coaching'
    | '/Services/Technical-rec'
    | '/Services/Training'
    | '/Services/Visa'
    | '/Services'
    | '/Candidates/applications/$id'
    | '/Candidates/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/Home'
    | '/about'
    | '/contact'
    | '/employers'
    | '/privacypolicy'
    | '/Candidates/applications'
    | '/Candidates/dashboard'
    | '/Candidates/deployment'
    | '/Candidates/documents'
    | '/Candidates/interviews'
    | '/Candidates/jobs'
    | '/Candidates/medical'
    | '/Candidates/notifications'
    | '/Candidates/offers'
    | '/Candidates/profile'
    | '/Candidates/visa'
    | '/Services/Doctors'
    | '/Services/Documentation'
    | '/Services/Grooming'
    | '/Services/Healthcare-rec'
    | '/Services/Mock-Interviews'
    | '/Services/Nurses'
    | '/Services/Nursing-rec'
    | '/Services/ParaMedical-tech'
    | '/Services/Prometric-coaching'
    | '/Services/Technical-rec'
    | '/Services/Training'
    | '/Services/Visa'
    | '/Services/'
    | '/Candidates/applications/$id'
    | '/Candidates/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  PrivacypolicyRoute: typeof PrivacypolicyRoute
  CandidatesApplicationsRoute: typeof CandidatesApplicationsRouteWithChildren
  CandidatesDashboardRoute: typeof CandidatesDashboardRoute
  CandidatesDeploymentRoute: typeof CandidatesDeploymentRoute
  CandidatesDocumentsRoute: typeof CandidatesDocumentsRoute
  CandidatesInterviewsRoute: typeof CandidatesInterviewsRoute
  CandidatesJobsRoute: typeof CandidatesJobsRouteWithChildren
  CandidatesMedicalRoute: typeof CandidatesMedicalRoute
  CandidatesNotificationsRoute: typeof CandidatesNotificationsRoute
  CandidatesOffersRoute: typeof CandidatesOffersRoute
  CandidatesProfileRoute: typeof CandidatesProfileRoute
  CandidatesVisaRoute: typeof CandidatesVisaRoute
  ServicesDoctorsRoute: typeof ServicesDoctorsRoute
  ServicesDocumentationRoute: typeof ServicesDocumentationRoute
  ServicesGroomingRoute: typeof ServicesGroomingRoute
  ServicesHealthcareRecRoute: typeof ServicesHealthcareRecRoute
  ServicesMockInterviewsRoute: typeof ServicesMockInterviewsRoute
  ServicesNursesRoute: typeof ServicesNursesRoute
  ServicesNursingRecRoute: typeof ServicesNursingRecRoute
  ServicesParaMedicalTechRoute: typeof ServicesParaMedicalTechRoute
  ServicesPrometricCoachingRoute: typeof ServicesPrometricCoachingRoute
  ServicesTechnicalRecRoute: typeof ServicesTechnicalRecRoute
  ServicesTrainingRoute: typeof ServicesTrainingRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacypolicy': {
      id: '/privacypolicy'
      path: '/privacypolicy'
      fullPath: '/privacypolicy'
      preLoaderRoute: typeof PrivacypolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/': {
      id: '/Services/'
      path: '/Services'
      fullPath: '/Services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Visa': {
      id: '/Services/Visa'
      path: '/Services/Visa'
      fullPath: '/Services/Visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Training': {
      id: '/Services/Training'
      path: '/Services/Training'
      fullPath: '/Services/Training'
      preLoaderRoute: typeof ServicesTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Technical-rec': {
      id: '/Services/Technical-rec'
      path: '/Services/Technical-rec'
      fullPath: '/Services/Technical-rec'
      preLoaderRoute: typeof ServicesTechnicalRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Prometric-coaching': {
      id: '/Services/Prometric-coaching'
      path: '/Services/Prometric-coaching'
      fullPath: '/Services/Prometric-coaching'
      preLoaderRoute: typeof ServicesPrometricCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/ParaMedical-tech': {
      id: '/Services/ParaMedical-tech'
      path: '/Services/ParaMedical-tech'
      fullPath: '/Services/ParaMedical-tech'
      preLoaderRoute: typeof ServicesParaMedicalTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Nursing-rec': {
      id: '/Services/Nursing-rec'
      path: '/Services/Nursing-rec'
      fullPath: '/Services/Nursing-rec'
      preLoaderRoute: typeof ServicesNursingRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Nurses': {
      id: '/Services/Nurses'
      path: '/Services/Nurses'
      fullPath: '/Services/Nurses'
      preLoaderRoute: typeof ServicesNursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Mock-Interviews': {
      id: '/Services/Mock-Interviews'
      path: '/Services/Mock-Interviews'
      fullPath: '/Services/Mock-Interviews'
      preLoaderRoute: typeof ServicesMockInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Healthcare-rec': {
      id: '/Services/Healthcare-rec'
      path: '/Services/Healthcare-rec'
      fullPath: '/Services/Healthcare-rec'
      preLoaderRoute: typeof ServicesHealthcareRecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Grooming': {
      id: '/Services/Grooming'
      path: '/Services/Grooming'
      fullPath: '/Services/Grooming'
      preLoaderRoute: typeof ServicesGroomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Documentation': {
      id: '/Services/Documentation'
      path: '/Services/Documentation'
      fullPath: '/Services/Documentation'
      preLoaderRoute: typeof ServicesDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Services/Doctors': {
      id: '/Services/Doctors'
      path: '/Services/Doctors'
      fullPath: '/Services/Doctors'
      preLoaderRoute: typeof ServicesDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/visa': {
      id: '/Candidates/visa'
      path: '/Candidates/visa'
      fullPath: '/Candidates/visa'
      preLoaderRoute: typeof CandidatesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/profile': {
      id: '/Candidates/profile'
      path: '/Candidates/profile'
      fullPath: '/Candidates/profile'
      preLoaderRoute: typeof CandidatesProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/offers': {
      id: '/Candidates/offers'
      path: '/Candidates/offers'
      fullPath: '/Candidates/offers'
      preLoaderRoute: typeof CandidatesOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/notifications': {
      id: '/Candidates/notifications'
      path: '/Candidates/notifications'
      fullPath: '/Candidates/notifications'
      preLoaderRoute: typeof CandidatesNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/medical': {
      id: '/Candidates/medical'
      path: '/Candidates/medical'
      fullPath: '/Candidates/medical'
      preLoaderRoute: typeof CandidatesMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/jobs': {
      id: '/Candidates/jobs'
      path: '/Candidates/jobs'
      fullPath: '/Candidates/jobs'
      preLoaderRoute: typeof CandidatesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/interviews': {
      id: '/Candidates/interviews'
      path: '/Candidates/interviews'
      fullPath: '/Candidates/interviews'
      preLoaderRoute: typeof CandidatesInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/documents': {
      id: '/Candidates/documents'
      path: '/Candidates/documents'
      fullPath: '/Candidates/documents'
      preLoaderRoute: typeof CandidatesDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/deployment': {
      id: '/Candidates/deployment'
      path: '/Candidates/deployment'
      fullPath: '/Candidates/deployment'
      preLoaderRoute: typeof CandidatesDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/dashboard': {
      id: '/Candidates/dashboard'
      path: '/Candidates/dashboard'
      fullPath: '/Candidates/dashboard'
      preLoaderRoute: typeof CandidatesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/applications': {
      id: '/Candidates/applications'
      path: '/Candidates/applications'
      fullPath: '/Candidates/applications'
      preLoaderRoute: typeof CandidatesApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Candidates/jobs/$id': {
      id: '/Candidates/jobs/$id'
      path: '/$id'
      fullPath: '/Candidates/jobs/$id'
      preLoaderRoute: typeof CandidatesJobsIdRouteImport
      parentRoute: typeof CandidatesJobsRoute
    }
    '/Candidates/applications/$id': {
      id: '/Candidates/applications/$id'
      path: '/$id'
      fullPath: '/Candidates/applications/$id'
      preLoaderRoute: typeof CandidatesApplicationsIdRouteImport
      parentRoute: typeof CandidatesApplicationsRoute
    }
  }
}

interface CandidatesApplicationsRouteChildren {
  CandidatesApplicationsIdRoute: typeof CandidatesApplicationsIdRoute
}

const CandidatesApplicationsRouteChildren: CandidatesApplicationsRouteChildren =
  {
    CandidatesApplicationsIdRoute: CandidatesApplicationsIdRoute,
  }

const CandidatesApplicationsRouteWithChildren =
  CandidatesApplicationsRoute._addFileChildren(
    CandidatesApplicationsRouteChildren,
  )

interface CandidatesJobsRouteChildren {
  CandidatesJobsIdRoute: typeof CandidatesJobsIdRoute
}

const CandidatesJobsRouteChildren: CandidatesJobsRouteChildren = {
  CandidatesJobsIdRoute: CandidatesJobsIdRoute,
}

const CandidatesJobsRouteWithChildren = CandidatesJobsRoute._addFileChildren(
  CandidatesJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  PrivacypolicyRoute: PrivacypolicyRoute,
  CandidatesApplicationsRoute: CandidatesApplicationsRouteWithChildren,
  CandidatesDashboardRoute: CandidatesDashboardRoute,
  CandidatesDeploymentRoute: CandidatesDeploymentRoute,
  CandidatesDocumentsRoute: CandidatesDocumentsRoute,
  CandidatesInterviewsRoute: CandidatesInterviewsRoute,
  CandidatesJobsRoute: CandidatesJobsRouteWithChildren,
  CandidatesMedicalRoute: CandidatesMedicalRoute,
  CandidatesNotificationsRoute: CandidatesNotificationsRoute,
  CandidatesOffersRoute: CandidatesOffersRoute,
  CandidatesProfileRoute: CandidatesProfileRoute,
  CandidatesVisaRoute: CandidatesVisaRoute,
  ServicesDoctorsRoute: ServicesDoctorsRoute,
  ServicesDocumentationRoute: ServicesDocumentationRoute,
  ServicesGroomingRoute: ServicesGroomingRoute,
  ServicesHealthcareRecRoute: ServicesHealthcareRecRoute,
  ServicesMockInterviewsRoute: ServicesMockInterviewsRoute,
  ServicesNursesRoute: ServicesNursesRoute,
  ServicesNursingRecRoute: ServicesNursingRecRoute,
  ServicesParaMedicalTechRoute: ServicesParaMedicalTechRoute,
  ServicesPrometricCoachingRoute: ServicesPrometricCoachingRoute,
  ServicesTechnicalRecRoute: ServicesTechnicalRecRoute,
  ServicesTrainingRoute: ServicesTrainingRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
